name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Container image
      run: docker build . --file Dockerfile --tag github-container-test:$(date +%s)
    - name: Push the Container image
      run: docker push docker.pkg.github.com/ctron/github-container-test/github-container-test:latest
