name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:

    - uses: actions/checkout@v1

    - name: Build the container image
      run: docker build . --file Dockerfile --tag github-container-test:${{ github.sha }}

    - name: Authenticate
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com --username ctron --password-stdin
    - name: Tag the container image
      run: docker tag github-container-test:${{ github.sha }} docker.pkg.github.com/ctron/github-container-test/github-container-test:latest
    - name: Push the container image
      run: docker push docker.pkg.github.com/ctron/github-container-test/github-container-test:latest
